version: '3'

services:
  web:
    container_name: fastify
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    volumes:
      - ./:/usr/src/app

  mongo:
    container_name: mongodb
    image: mongo
    ports: 
      - "27017:27017"
    